# Use postgres/example user/password credentials
version: '3.7'

services:
  web-app:
    build: .
    command: npm start
    ports:
      - '3000:3000'

  db-docker:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: dashboard
      #PGPORT default: 5432
      PGPORT: 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      #Default for outside:inside is 5432:5432
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
